localizedError: add EROS (readonly device) handling
Also refactored getLocalizedError using a regex instead of a dozen cases
with the same code: should make it a lot easier to update.